-- PostgreSQL production schema. The local demo currently uses an in-memory repository.
create type node_status as enum ('REGISTERING','ONLINE','DEGRADED','PAUSED','OFFLINE','SUSPENDED','RETIRED');
create table users (id uuid primary key, email text unique not null, password_salt text not null, password_hash text not null, created_at timestamptz not null default now());
create table sessions (token_hash text primary key, user_id uuid not null references users(id) on delete cascade, expires_at timestamptz not null, created_at timestamptz not null default now());
create table storage_accounts (user_id uuid primary key references users(id), quota_bytes bigint not null, used_bytes bigint not null default 0);
create table storage_nodes (id uuid primary key, user_id uuid not null references users(id), device_id text not null, public_key text not null, region text not null, platform text not null, pledged_bytes bigint not null check (pledged_bytes >= 0), available_bytes bigint not null, used_bytes bigint not null default 0, reliability_score numeric not null, status node_status not null, last_seen timestamptz not null);
create table files (id uuid primary key, user_id uuid not null references users(id), name text not null, size_bytes bigint not null check(size_bytes > 0), encryption_algorithm text not null default 'AES-256-GCM', wrapped_key text not null, key_nonce text not null, key_tag text not null, created_at timestamptz not null default now());
create table file_chunks (id uuid primary key, file_id uuid not null references files(id) on delete cascade, ordinal integer not null, hash text not null, storage_hash text not null, bytes bigint not null check(bytes > 0), nonce text not null, tag text not null, unique(file_id, ordinal));
create table chunk_replicas (chunk_id uuid references file_chunks(id), node_id uuid references storage_nodes(id), verified boolean not null default false, primary key(chunk_id,node_id));
create table credit_ledger (id uuid primary key, account_id uuid not null references users(id), amount numeric not null check(amount <> 0), entry_type text not null, reference text not null, created_at timestamptz not null default now());
create index storage_nodes_status_idx on storage_nodes(status); create index files_user_idx on files(user_id); create index file_chunks_file_idx on file_chunks(file_id); create index credit_ledger_account_idx on credit_ledger(account_id,created_at); create index sessions_expiry_idx on sessions(expires_at);
